name: run push images

on:
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ccr.ccs.tencentyun.com
  REPOSITORY: pixiuio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: publish kubernetes or custom images
        run: chmod +x ./app && ./app -v 2 --harbor ${{ env.REGISTRY }} --image-repository ${{ env.REPOSITORY }} --user 100015412243 --password 123456AA
